/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package habibe_gurel_1921221034_networklab_2023_proje2;

import Client.Client;
import Message.Message;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 * Project 2
 * @author Habibe Gurel 1921221034
 */
public class chat extends javax.swing.JFrame {

    /**
     * Creates new form chat
     */
    public static String name;
    public DefaultListModel peopleListModel = new DefaultListModel();
    public DefaultListModel roomListModel = new DefaultListModel();
    public static chat mychat;
    public int control = 1;
    public String senderPerson = "";
    public static ArrayList<String> messageArr = new ArrayList<>();

    public chat() {
        initComponents();
        mychat = this;
        list_people.setModel(peopleListModel);
        list_rooms.setModel(roomListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane_chat = new javax.swing.JTabbedPane();
        pnl_chat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_chat = new javax.swing.JTextArea();
        txtField_message = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        btn_documents = new javax.swing.JButton();
        lbl_person = new javax.swing.JLabel();
        lbl_personicon = new javax.swing.JLabel();
        pnl_people = new javax.swing.JPanel();
        lbl_me = new javax.swing.JLabel();
        lbl_myname = new javax.swing.JLabel();
        pnl_otherPeople = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_people = new javax.swing.JList<>();
        btn_startChatting = new javax.swing.JButton();
        pnl_rooms = new javax.swing.JPanel();
        txt_roomName = new javax.swing.JTextField();
        btn_createRoom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_rooms = new javax.swing.JList<>();
        btn_joinRoom = new javax.swing.JButton();
        pnl_roomChat = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea_roomMessages = new javax.swing.JTextArea();
        txt_roomMessage = new javax.swing.JTextField();
        btn_roomSend = new javax.swing.JButton();
        btn_roomDocument = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_roomsName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHAT APP");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabbedPane_chat.setForeground(new java.awt.Color(255, 255, 255));

        pnl_chat.setBackground(new java.awt.Color(0, 102, 153));

        txtArea_chat.setEditable(false);
        txtArea_chat.setColumns(20);
        txtArea_chat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtArea_chat.setRows(5);
        txtArea_chat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtArea_chat);

        txtField_message.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtField_message.setForeground(new java.awt.Color(153, 153, 153));
        txtField_message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtField_messageMousePressed(evt);
            }
        });
        txtField_message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtField_messageKeyReleased(evt);
            }
        });

        btn_send.setBackground(new java.awt.Color(0, 102, 153));
        btn_send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/Send.png"))); // NOI18N
        btn_send.setEnabled(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_documents.setBackground(new java.awt.Color(0, 102, 153));
        btn_documents.setForeground(new java.awt.Color(60, 63, 65));
        btn_documents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/file.png"))); // NOI18N
        btn_documents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_documentsActionPerformed(evt);
            }
        });

        lbl_person.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        lbl_personicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/person.png"))); // NOI18N

        javax.swing.GroupLayout pnl_chatLayout = new javax.swing.GroupLayout(pnl_chat);
        pnl_chat.setLayout(pnl_chatLayout);
        pnl_chatLayout.setHorizontalGroup(
            pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(pnl_chatLayout.createSequentialGroup()
                        .addComponent(btn_documents, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_chatLayout.createSequentialGroup()
                        .addComponent(lbl_personicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_chatLayout.setVerticalGroup(
            pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_personicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_documents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtField_message, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        tabbedPane_chat.addTab("CHAT", pnl_chat);

        pnl_people.setBackground(new java.awt.Color(0, 102, 153));

        lbl_me.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_me.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/person.png"))); // NOI18N
        lbl_me.setText("ME :");

        lbl_myname.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        pnl_otherPeople.setBackground(new java.awt.Color(0, 102, 153));

        list_people.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        list_people.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_peopleValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(list_people);

        btn_startChatting.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_startChatting.setForeground(new java.awt.Color(0, 0, 0));
        btn_startChatting.setText("START CHATTING");
        btn_startChatting.setEnabled(false);
        btn_startChatting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startChattingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_otherPeopleLayout = new javax.swing.GroupLayout(pnl_otherPeople);
        pnl_otherPeople.setLayout(pnl_otherPeopleLayout);
        pnl_otherPeopleLayout.setHorizontalGroup(
            pnl_otherPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_otherPeopleLayout.createSequentialGroup()
                .addGroup(pnl_otherPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addComponent(btn_startChatting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_otherPeopleLayout.setVerticalGroup(
            pnl_otherPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_otherPeopleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_startChatting, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_peopleLayout = new javax.swing.GroupLayout(pnl_people);
        pnl_people.setLayout(pnl_peopleLayout);
        pnl_peopleLayout.setHorizontalGroup(
            pnl_peopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_peopleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_peopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_otherPeople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_peopleLayout.createSequentialGroup()
                        .addComponent(lbl_me, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_myname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_peopleLayout.setVerticalGroup(
            pnl_peopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_peopleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_peopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_me, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_myname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_otherPeople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane_chat.addTab("PEOPLE", pnl_people);

        pnl_rooms.setBackground(new java.awt.Color(0, 102, 153));

        txt_roomName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        btn_createRoom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_createRoom.setForeground(new java.awt.Color(0, 0, 0));
        btn_createRoom.setText("CREATE ROOM");
        btn_createRoom.setEnabled(false);
        btn_createRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_createRoomMouseEntered(evt);
            }
        });
        btn_createRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createRoomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("ENTER A ROOM NAME :");

        list_rooms.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        list_rooms.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_roomsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(list_rooms);

        btn_joinRoom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_joinRoom.setForeground(new java.awt.Color(0, 0, 0));
        btn_joinRoom.setText("JOIN ROOM");
        btn_joinRoom.setEnabled(false);
        btn_joinRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_roomsLayout = new javax.swing.GroupLayout(pnl_rooms);
        pnl_rooms.setLayout(pnl_roomsLayout);
        pnl_roomsLayout.setHorizontalGroup(
            pnl_roomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_roomsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_roomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_joinRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_roomsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_roomName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_createRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_roomsLayout.setVerticalGroup(
            pnl_roomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_roomsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_roomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_roomName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(btn_createRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_joinRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane_chat.addTab("ROOMS", pnl_rooms);

        pnl_roomChat.setBackground(new java.awt.Color(0, 102, 153));

        txtArea_roomMessages.setEditable(false);
        txtArea_roomMessages.setColumns(20);
        txtArea_roomMessages.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtArea_roomMessages.setRows(5);
        jScrollPane4.setViewportView(txtArea_roomMessages);

        txt_roomMessage.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_roomMessage.setForeground(new java.awt.Color(153, 153, 153));
        txt_roomMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_roomMessageMousePressed(evt);
            }
        });
        txt_roomMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_roomMessageKeyReleased(evt);
            }
        });

        btn_roomSend.setBackground(new java.awt.Color(0, 102, 153));
        btn_roomSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/Send.png"))); // NOI18N
        btn_roomSend.setEnabled(false);
        btn_roomSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomSendActionPerformed(evt);
            }
        });

        btn_roomDocument.setBackground(new java.awt.Color(0, 102, 153));
        btn_roomDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/file.png"))); // NOI18N
        btn_roomDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomDocumentActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habibe_gurel_1921221034_networklab_2023_proje2/icons/people.png"))); // NOI18N

        lbl_roomsName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        javax.swing.GroupLayout pnl_roomChatLayout = new javax.swing.GroupLayout(pnl_roomChat);
        pnl_roomChat.setLayout(pnl_roomChatLayout);
        pnl_roomChatLayout.setHorizontalGroup(
            pnl_roomChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_roomChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_roomChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(pnl_roomChatLayout.createSequentialGroup()
                        .addComponent(btn_roomDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_roomMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_roomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(pnl_roomChatLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_roomsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_roomChatLayout.setVerticalGroup(
            pnl_roomChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_roomChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_roomChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_roomsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_roomChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_roomChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_roomMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(btn_roomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btn_roomDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        tabbedPane_chat.addTab("ROOM CHAT", pnl_roomChat);

        getContentPane().add(tabbedPane_chat, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_messageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtField_messageMousePressed
        txtField_message.setText("");
        txtField_message.setForeground(Color.black);
    }//GEN-LAST:event_txtField_messageMousePressed

    private void btn_documentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_documentsActionPerformed
        JFileChooser j = new JFileChooser("C:");
        j.showSaveDialog(null);
    }//GEN-LAST:event_btn_documentsActionPerformed

    private void btn_joinRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinRoomActionPerformed
        tabbedPane_chat.setSelectedIndex(3);//chat sayfasina doner
        lbl_roomsName.setText(list_rooms.getSelectedValue());//room adini alir label ismini gunceller
        txtArea_roomMessages.setText("");
        Message msg = new Message(Message.Message_Type.GetRoomMessage);//onceki mesajlari da alabilmek için GetRoomMessage tipinde mesaj olusturuyorum
        msg.content = lbl_roomsName.getText();//bulundugum odanin adini mesaj olarak servera yolluyorum
        Client.Send(msg);
    }//GEN-LAST:event_btn_joinRoomActionPerformed

    private void btn_createRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createRoomActionPerformed
        // TODO add your handling code here:
        String roomName = txt_roomName.getText();
        roomListModel.addElement(roomName);//yeni olusturulan room listeye eklenir
        Message msg = new Message(Message.Message_Type.CreateRoom);//CreateRoom tipinde mesaj olusturulur
        msg.content = roomName;//mesaj icerigi room ismi
        Client.Send(msg);//servera mesaj gonderilir
    }//GEN-LAST:event_btn_createRoomActionPerformed

    private void btn_startChattingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startChattingActionPerformed
        // TODO add your handling code here:
        lbl_person.setText(list_people.getSelectedValue());//secilen kisiyle mesajlasma baslatilir
        tabbedPane_chat.setSelectedIndex(0);//chat sayfasina gidilir
        txtArea_chat.setText("");
        for (int i = 0; i < messageArr.size(); i++) {
            if (i % 2 == 0 && messageArr.get(i).equals(lbl_person.getText())) {//ilk indexte kisi tutuyorum
                txtArea_chat.setText(messageArr.get(i + 1));//i+1. indexte mesaj tutuyorum
            }
        }
    }//GEN-LAST:event_btn_startChattingActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        String sendmsg = lbl_myname.getText() + ":  " + txtField_message.getText() + "\n";//kisi adi: mesaj
        Message msg = new Message(Message.Message_Type.SendMessage);
        msg.content = lbl_person.getText();//yollanacak kisi
        Client.Send(msg);
        Message msg2 = new Message(Message.Message_Type.SendMessage);
        msg2.content = sendmsg;
        Client.Send(msg2);

        int cnt = 0;//control
        for (int i = 0; i < messageArr.size(); i++) {
            if (i % 2 == 0 && messageArr.get(i).equals(lbl_person.getText())) {
                String oldmsg = messageArr.get(i + 1);
                oldmsg = oldmsg + sendmsg;
                messageArr.set(i + 1, oldmsg);
                txtArea_chat.setText(messageArr.get(i + 1));
                cnt = 1;//kisi var
            }
        }
        if (cnt == 0) {//kisi yoksa
            messageArr.add(lbl_person.getText());
            messageArr.add(sendmsg);
            txtArea_chat.setText(sendmsg);
        }
        txtField_message.setText("");
        btn_send.setEnabled(false);
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_roomDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomDocumentActionPerformed
        JFileChooser j = new JFileChooser("C:");
        j.showSaveDialog(null);
    }//GEN-LAST:event_btn_roomDocumentActionPerformed

    private void btn_roomSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomSendActionPerformed
        String sendmsg = lbl_myname.getText() + ":  " + txt_roomMessage.getText() + "\n";//kisi adi: mesaj
        Message msg = new Message(Message.Message_Type.SendRoomMessage);
        msg.content = lbl_roomsName.getText();//yollanacak oda
        Client.Send(msg);
        Message msg2 = new Message(Message.Message_Type.SendRoomMessage);
        msg2.content = sendmsg;
        Client.Send(msg2);
        txt_roomMessage.setText("");
        btn_roomSend.setEnabled(false);
    }//GEN-LAST:event_btn_roomSendActionPerformed

    private void txt_roomMessageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_roomMessageMousePressed
        // TODO add your handling code here:
        txt_roomMessage.setText("");
        txt_roomMessage.setForeground(Color.black);
    }//GEN-LAST:event_txt_roomMessageMousePressed

    private void btn_createRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createRoomMouseEntered
        if (txt_roomName.getText().isEmpty()) {
            btn_createRoom.setEnabled(false);
        } else {
            btn_createRoom.setEnabled(true);
        }
    }//GEN-LAST:event_btn_createRoomMouseEntered

    private void list_peopleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_peopleValueChanged
        // TODO add your handling code here:
        btn_startChatting.setEnabled(true);
    }//GEN-LAST:event_list_peopleValueChanged

    private void list_roomsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_roomsValueChanged
        // TODO add your handling code here:
        btn_joinRoom.setEnabled(true);
    }//GEN-LAST:event_list_roomsValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Message msg = new Message(Message.Message_Type.Bitis);//bitis tipinde mesaj olusturuyorum
        msg.content = lbl_myname.getText();
        Client.Send(msg);//Servera kapatan clientin adini yollar
        Client.Stop();//clienti durdurur
    }//GEN-LAST:event_formWindowClosing

    private void txt_roomMessageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_roomMessageKeyReleased
        // TODO add your handling code here:
         if(txt_roomMessage.getText().isEmpty()){
            btn_roomSend.setEnabled(false);
        }else{
            btn_roomSend.setEnabled(true);
        }
    }//GEN-LAST:event_txt_roomMessageKeyReleased

    private void txtField_messageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField_messageKeyReleased
        // TODO add your handling code here:
         if(txtField_message.getText().isEmpty()){
            btn_send.setEnabled(false);
        }else{
            btn_send.setEnabled(true);
        }
    }//GEN-LAST:event_txtField_messageKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createRoom;
    private javax.swing.JButton btn_documents;
    private javax.swing.JButton btn_joinRoom;
    private javax.swing.JButton btn_roomDocument;
    private javax.swing.JButton btn_roomSend;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_startChatting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_me;
    public javax.swing.JLabel lbl_myname;
    public javax.swing.JLabel lbl_person;
    private javax.swing.JLabel lbl_personicon;
    private javax.swing.JLabel lbl_roomsName;
    public javax.swing.JList<String> list_people;
    private javax.swing.JList<String> list_rooms;
    private javax.swing.JPanel pnl_chat;
    private javax.swing.JPanel pnl_otherPeople;
    private javax.swing.JPanel pnl_people;
    private javax.swing.JPanel pnl_roomChat;
    private javax.swing.JPanel pnl_rooms;
    private javax.swing.JTabbedPane tabbedPane_chat;
    public javax.swing.JTextArea txtArea_chat;
    public javax.swing.JTextArea txtArea_roomMessages;
    private javax.swing.JTextField txtField_message;
    private javax.swing.JTextField txt_roomMessage;
    private javax.swing.JTextField txt_roomName;
    // End of variables declaration//GEN-END:variables
}
